encoder: stft
encoder_conf:
    n_fft: 512
    hop_length: 128
decoder: stft
decoder_conf:
    n_fft: 512
    hop_length: 128
separator: rnn
separator_conf:
    rnn_type: blstm
    num_spk: 1
    nonlinear: relu
    layer: 1
    unit: 128
    dropout: 0.2

criterions:
    # The first criterion
    - name: si_snr
      conf:
          eps: 1.0e-7
      # the wrapper for the current criterion
      # for single-talker case, we simplely use fixed_order wrapper
      wrapper: fixed_order
      wrapper_conf:
          weight: 1.0
