# This configuration requires 4 GPUs with 32GB memory
batch_type: numel
batch_bins: 11250000
accum_grad: 8
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

# network architecture
# freeze_param: ["decoder"]

input_size: 2048
encoder: wav2vec2
encoder_conf:
    output_size: 512
    use_transformer_layer: false
    transformer_layer_num: 2
    w2v_url: ./exp/w2v_csj_20221112/checkpoint_best.pt

    # predecoder: minitransformer
    # predecoder_conf:
    #     output_size: 512
    #     transformer_layer_num: 1
    #     normalize_before: true
    #     normalize_after: true
    #     dropout_rate: 0.1
    #     attention_heads: 4
    #     attention_dropout_rate: 0.0
    #     linear_units: 2048

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0
    lsm_weight: 0.1
    length_normalized_loss: false

# optimization related
optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend: null

normalize: null

specaug: null
